sudo: required
services:
- docker
language: python
env:
  global:
  - IMAGE="bearn/testapp"
  - REGISTRY_USER=bearn
  - secure: oWiQrSnnoDl5rIvaPhMipBQIH7YiDhDfXccy/AmVc2mremt5gmKgLXJH+5UzqbJ4vo6pG5M49UPdIw8mViIWqAzxtVjp1yztdjN5fDcp9tDuZb7AlmFdf8l9LwxxM9KBE5+ACVV4Hue36p1/zVeed/NlNiIsxBZNX0FaoFBYul2gyGh9TFPPP6iocleCDMWCpII4I3O0R3Y782qa9oTQH2hrDzv9w9HDARXHcyKG2KYTwqAI3q/u81K3DLYCq5K2L07eKNeRiEFTU9/RB7fkMizs4ErZd2hlRNIwmkWGMm+H6SNQSTVo93XQLyAs5aIf10kgr5rU0Ks7/SourUU7eeBURCvfytZ71zEW+VjFDaDe9//2mX3LcD8yrIxofNzC6vwDy6Z0bKT2HIBXblqDvw3Uuq+Rd7vDhXZxwb/OeixW3o+oX2jkM/Q1c9crZNP5d/sqRs82VQVHjbBIxXLXFJDyozWeCPaQq/5Nt/LOmvDlTYPsDRioXU98UU6ULR7/bOxrD0x3D3nCXrKvCz0vQeykVzzCEj78FbLTmDN+Uj+USHmmfk2zGdF9FcAMwmTWwM8k0vVoJtDUCRfzCeU72qTL9mddWF6+8pqLgrG0MuXugucko1GYUWG4IRWKI9uoSrfV2M+A/Q2ZoqF6wR+2ivtD66gJylpus5q6MnNEPvI=
before_install:
- sudo apt-get update
- sudo apt-get install -qy -o Dpkg::Options::="--force-confold" docker-engine
install: []
before_script:
- version="$(awk '$2 == "TESTAPP_VERSION" { print $3; exit }' Dockerfile | cut -d'~' -f1)"
- printenv  
- docker pull "$IMAGE"
script:
- docker build --pull --cache-from "$IMAGE" -t "$IMAGE" .
before_deploy:
- pip install docker-ci-deploy==0.2.0
- docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD"
deploy:
  provider: script
  script: dcd --tag-version "$version" --tag-semver --tag-latest "$IMAGE"
  on:
    branch: master
